name: Translator
main: me.kyllian.translator.TranslatorPlugin
version: 0.081
description: Translator plugin
depend: [ProtocolLib]

commands:
  language:
    usage: /<command>
    aliases: [lang]
  translator:
    usage: /<command>
    aliases: [translate]