name: Translator
main: me.kyllian.translator.TranslatorPlugin
version: 0.1
description: Translator plugin
depend: [ProtocolLib]
api-version: 1.15

commands:
  language:
    usage: /<command>
    aliases: [lang]
  translator:
    usage: /<command>
    aliases: [translate]